version: '3.8'
services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-sb
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: dbschoolmanager
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - "3308:3308"
    expose:
      - 3308
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynetwork

  school-manager:
    image: figueiredoisaac/school-manager
    container_name: school-manager-v2
    restart: always
    build: ./
    working_dir: /
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://mysql-db:3308/dbschoolmanager?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.MYSQL_DATABASE: dbschoolmanager
      SPRING.DATASOURCE.PASSWORD: root
      SPRING.DATASOURCE.DRIVER: com.mysql.cj.jdbc.Driver
    ports:
      - "8080:8080"
    command: mvn spring-boot:run
    depends_on:
      - mysql-db
    networks:
      - mynetwork
    volumes:
      - ./target:/app/target

volumes:
  mysql-data:
    driver: local

networks:
  mynetwork:
    driver: bridge