server:
  port:80

spring:
   datasource:
       url: jdbc:mysql://localhost:3306/dbschoolmanager?useTimezone=true&serverTimezone=UTC&autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true
       username: root
       password: u$Isaac
       driver-class-name: com.mysql.cj.jdbc.Driver

   flyway:
     enabled: true
     repair-on-mismatch: true
     clean-on-validation-error: true
     locations: classpath:db/migration

   jpa:
       hibernate:
         ddl-auto: none
       show-sql: false

   application:
     name: school-manager

spring-doc:
  pathsToMatch: /v1/**
  swagger-ui:
      use-root-path: true