CREATE TABLE USERS (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(45) NULL,
  username VARCHAR(20) NULL,
  email VARCHAR(45) NULL,
  password VARCHAR(100) NULL,
  role VARCHAR(45) NULL,
  created_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
